apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-deployment
  labels:
    app: pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet
  template:
    metadata:
      labels:
        app: pet
    spec:
      containers:
        - name: pet
          image: vimanthan/pet:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pet-service
spec:
  selector:
    app: pet
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
